# Author Yash
FROM openjdk:8-jdk-alpine

EXPOSE 8080

RUN mkdir -p /var/app/code-server-api
COPY target/ecom.jar /var/app/code-server-api/

CMD java -jar /var/app/code-server-api/ecom > log1.txt 2>&1